DROP TABLE IF EXISTS hits CASCADE;

CREATE TABLE IF NOT EXISTS hit
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app       varchar(100)                            NOT NULL,
    uri       varchar(100)                            NOT NULL,
    ip        varchar(100)                            NOT NULL,
    timestamp TIMESTAMP                               NOT NULL,
    CONSTRAINT pk_stats PRIMARY KEY (id)
);