version: '3.1'
services:
  stats-server:
    build: ewm-status
    image: ewm-status_image
    container_name: ewm-status_container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm_status_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password

  stats-db:
    image: postgres:14-alpine
    container_name: stats_db_container
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm_status_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

  ewm-service:
    build: ewm-main
    image: ewm-main_image
    container_name: ewm_main_container
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm_main_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - EWM_STATUS_URL=http://stats-server:9090

  ewm-db:
    image: postgres:14-alpine
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm_main_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
